check output

diff --git a/.github/workflows/run_notebook.yml b/.github/workflows/run_notebook.yml
--- a/.github/workflows/run_notebook.yml
+++ b/.github/workflows/run_notebook.yml
@@ -27,4 +27,17 @@ jobs:
             - name: Get Notebook Output
               run: |
                 echo "Notebook output: ${{ steps.run-notebook.outputs.notebook-output }}"
-                echo "${{ steps.run-notebook.outputs.notebook-output }}" > notebook_output_${{ steps.run-notebook.outputs.run_id }}.json
+                - name: Save Notebook Output
+                  run: |
+                    echo "${{ steps.run-notebook.outputs.notebook-output }}" > notebook_output_${{ steps.run-notebook.outputs.run_id }}.json
+
+            - name: Check Notebook Output
+              run: |
+                status=$(jq -r '.test_summary_status' notebook_output_${{ steps.run-notebook.outputs.run_id }}.json)
+                if [ "$status" == "FAIL" ]; then
+                    echo "Notebook test failed"
+                    exit 1
+                else
+                    echo "Notebook test passed"
+                fi
+                shell: bash
